import { randomUUID } from "node:crypto";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { sandboxAccessVerified } from "@/lib/beta-controls";
import { prisma } from "@/lib/prisma";
import { realMarketCustomerTestEnabled } from "@/lib/real-market";
import { ensureScoutWallet, visibleScoutOrders } from "@/lib/scout-market";
import { formatRealMoney as money } from "@/lib/real-market-sandbox";

export const metadata = { title: "Scouting Economy Test Market | NexAthleteXchange", robots: { index: false, follow: false } };
const action = "/api/real-market/test/actions";
function cashForm(type: "DEPOSIT" | "WITHDRAWAL") {
  return <form className="card realSandboxForm" action={action} method="post"><h3>{type === "DEPOSIT" ? "Add fake cash" : "Withdraw fake cash"}</h3><input type="hidden" name="action" value="CASH"/><input type="hidden" name="type" value={type}/><input type="hidden" name="requestKey" value={randomUUID()}/><label>Test amount<input name="amount" type="number" min="0.01" max="1000000" step="0.01" defaultValue={type === "DEPOSIT" ? "1000" : "25"} required/></label><button className={type === "WITHDRAWAL" ? "secondary" : ""}>{type === "DEPOSIT" ? "Add test cash" : "Test withdrawal"}</button><small>No bank, card, or crypto transfer takes place.</small></form>;
}

export default async function ScoutTestMarket({ searchParams }: { searchParams: Promise<{ athlete?: string; notice?: string; error?: string }> }) {
  if (!realMarketCustomerTestEnabled()) redirect("/real-market");
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  if (!(await sandboxAccessVerified(user.id))) redirect("/real-market/verify");
  const params = await searchParams;
  const control = await prisma.betaControl.findUnique({ where: { id: "global" } });
  const account = await ensureScoutWallet(user.id);
  const instruments = await prisma.realMarketInstrument.findMany({ where: { environment: "SANDBOX", status: { not: "RETIRED" } }, include: { athlete: true }, orderBy: [{ athlete: { sport: "asc" } }, { athlete: { name: "asc" } }], take: 60 });
  const selected = instruments.find(item => item.athleteId === params.athlete) || instruments[0];
  const athleteId = selected?.athleteId;
  const [positions, orders, fills, entries, grant, bids, asks] = await Promise.all([
    prisma.scoutPosition.findMany({ where: { userId: user.id, quantity: { gt: 0 } }, include: { athlete: true }, orderBy: { athlete: { name: "asc" } } }),
    prisma.scoutOrder.findMany({ where: { userId: user.id }, include: { athlete: true }, orderBy: { sequence: "desc" }, take: 40 }),
    prisma.scoutFill.findMany({ where: { OR: [{ buyOrder: { userId: user.id } }, { sellOrder: { userId: user.id } }] }, include: { buyOrder: { include: { athlete: true } }, sellOrder: true }, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: 20 }),
    prisma.scoutLedgerEntry.findMany({ where: { userId: user.id }, orderBy: { sequence: "desc" }, take: 20 }),
    athleteId ? prisma.scoutInventoryGrant.findUnique({ where: { userId_athleteId: { userId: user.id, athleteId } } }) : null,
    athleteId ? prisma.scoutOrder.groupBy({ by: ["price"], where: { ...visibleScoutOrders(athleteId), side: "BUY" }, _sum: { remaining: true }, orderBy: { price: "desc" }, take: 10 }) : [],
    athleteId ? prisma.scoutOrder.groupBy({ by: ["price"], where: { ...visibleScoutOrders(athleteId), side: "SELL" }, _sum: { remaining: true }, orderBy: { price: "asc" }, take: 10 }) : [],
  ]);
  const referenceValue = positions.reduce((sum, p) => sum + Number(p.quantity) * Number(p.athlete.currentPrice), 0);
  const open = selected?.status === "ACTIVE" && selected.athlete.active && selected.athlete.marketEnabled && !control?.sandboxPaused;
  return <main className="realSandboxPage shell">
    <header className="realSandboxHeader"><div><div className="realMarketBadge sandboxBadge">CUSTOMER TEST MARKET • FAKE MONEY</div><h1>Put your scouting conviction to the test.</h1><p className="muted">Fund a limit order, trade with another verified tester, and follow every fill. This market matches customer orders; it never supplies an automatic buyer.</p></div><Link className="button secondary" href="/real-market">Real Market plan</Link></header>
    {params.notice && <div role="status" className="notice successNotice">{params.notice}</div>}{params.error && <div role="alert" className="notice errorNotice">{params.error}</div>}
    <section className="realSandboxStats"><article className="card"><span>Available test cash</span><strong>{money(account.balance.sub(account.reservedCash))}</strong><small>Can back new orders or fake withdrawals</small></article><article className="card"><span>Cash held for orders</span><strong>{money(account.reservedCash)}</strong><small>Release unfilled holds by canceling</small></article><article className="card"><span>Total test cash</span><strong>{money(account.balance)}</strong><small>Includes cash held for orders</small></article><article className="card"><span>Reference holdings value</span><strong>{money(referenceValue)}</strong><small>Research valuation; not withdrawable cash</small></article></section>
    <section className="realSandboxSection"><div className="realMarketSectionHead"><span className="landingEyebrow">TEST BALANCE</span><h2>Start with fake cash.</h2></div><div className="realSandboxFundingGrid withdrawalGrid">{cashForm("DEPOSIT")}{cashForm("WITHDRAWAL")}</div></section>
    <section className="realSandboxSection"><div className="realMarketSectionHead"><span className="landingEyebrow">THE SCOUTING ECONOMY</span><h2>Choose your athlete.</h2></div><form className="scoutSelector" method="get"><label>Athlete<select name="athlete" defaultValue={athleteId}>{instruments.map(item => <option key={item.id} value={item.athleteId}>{item.athlete.sport} • {item.athlete.name} • {item.status}</option>)}</select></label><button>Open order book</button></form>
    {!selected ? <div className="card realSandboxEmpty">The test market is being prepared. Check back shortly.</div> : <>
      <div className="scoutBookHeading"><div><h3>{selected.athlete.name}</h3><p className="muted">Performance reference: {money(selected.athlete.currentPrice)} • {open ? "Open for test orders" : "Orders paused"}</p></div><Link className="button secondary" href={`/real-market/test?athlete=${encodeURIComponent(selected.athleteId)}`}>Refresh order book</Link></div>
      <div className="scoutTwoUp">{[["Funded buy interest", bids], ["Backed sell interest", asks]].map(([title, levels]) => <article key={String(title)} className="card scoutBook"><h3>{String(title)}</h3>{!open ? <p>Trading is paused for this athlete.</p> : (levels as typeof bids).length === 0 ? <p className="muted">No resting orders.</p> : <table><thead><tr><th>Limit price</th><th>Available shares</th></tr></thead><tbody>{(levels as typeof bids).map(level => <tr key={String(level.price)}><td>{money(level.price)}</td><td>{Number(level._sum.remaining).toFixed(2)}</td></tr>)}</tbody></table>}<small>Top 10 price levels. Refresh for current interest.</small></article>)}</div>
      <div className="scoutTwoUp">{(["BUY", "SELL"] as const).map(side => <form key={side} className="card realSandboxForm" action={action} method="post"><h3>{side === "BUY" ? "Place a buy order" : "Place a sell order"}</h3><input type="hidden" name="action" value="ORDER"/><input type="hidden" name="athleteId" value={selected.athleteId}/><input type="hidden" name="side" value={side}/><input type="hidden" name="requestKey" value={randomUUID()}/><label>{side === "BUY" ? "Maximum buy price" : "Minimum sell price"}<input name="price" type="number" min="0.01" max="1000000" step="0.01" defaultValue={Number(selected.athlete.currentPrice).toFixed(2)} required/></label><label>Shares<input name="quantity" type="number" min="0.01" max="1000000" step="0.01" defaultValue="1" required/></label><button disabled={!open}>{side === "BUY" ? "Submit test buy" : "Submit test sell"}</button><small>{side === "BUY" ? "Reserves limit-price cost plus a $2 fee." : "Reserves your shares and $2 of test cash for the fee."} One $2 fee per order on its first fill, including partial fills. Later fills of that order add no fee. No fill means no fee.</small></form>)}</div>
      <div className="card scoutAllocation"><h3>Test shares for your first sell</h3><p>Each verified tester can claim 10 fake shares of this athlete once. They carry zero test cost basis and no real value. This allocation is for testing, not a live issuance policy.</p>{grant ? <strong>Allocation already claimed.</strong> : <form action={action} method="post"><input type="hidden" name="action" value="GRANT"/><input type="hidden" name="athleteId" value={selected.athleteId}/><button disabled={!open}>Claim 10 fake shares</button></form>}</div>
    </>}</section>
    <section className="realSandboxSection"><div className="realMarketSectionHead"><h2>Your orders.</h2><p className="muted">Best price first, then arrival order. Executions use the resting order's price. Your own orders cannot match each other. Canceling a partial order keeps completed fills and their first-fill fee.</p></div><div className="realSandboxTableWrap card"><table className="realSandboxTable"><thead><tr><th>Athlete</th><th>Side</th><th>Limit</th><th>Filled / total</th><th>Status</th><th>Cash hold</th><th>Fee paid</th><th>Action</th></tr></thead><tbody>{orders.map(order => <tr key={order.id}><td>{order.athlete.name}</td><td>{order.side}</td><td>{money(order.price)}</td><td>{Number(order.quantity.sub(order.remaining)).toFixed(2)} / {Number(order.quantity).toFixed(2)}</td><td>{order.status}<small>{order.cancelReason}</small></td><td>{money(order.cashHold)}</td><td>{money(order.feePaid)}</td><td>{["OPEN", "PARTIAL"].includes(order.status) && <form action={action} method="post"><input type="hidden" name="action" value="CANCEL"/><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="athleteId" value={order.athleteId}/><button className="secondary">Cancel remainder</button></form>}</td></tr>)}</tbody></table>{orders.length === 0 && <p className="realSandboxEmpty">No orders yet.</p>}</div></section>
    <section className="realSandboxSection"><h2>Your test positions.</h2><div className="realSandboxTableWrap card"><table className="realSandboxTable"><thead><tr><th>Athlete</th><th>Total shares</th><th>Held for sells</th><th>Available shares</th><th>Test cost basis</th><th>Reference value</th></tr></thead><tbody>{positions.map(p => <tr key={p.id}><td>{p.athlete.name}</td><td>{Number(p.quantity).toFixed(2)}</td><td>{Number(p.reservedQuantity).toFixed(2)}</td><td>{Number(p.quantity.sub(p.reservedQuantity)).toFixed(2)}</td><td>{money(p.costBasis)}</td><td>{money(Number(p.quantity) * Number(p.athlete.currentPrice))}</td></tr>)}</tbody></table>{positions.length === 0 && <p className="realSandboxEmpty">No test positions yet. Claim a fake allocation or match a buy order.</p>}</div></section>
    <section className="realSandboxSection scoutTwoUp"><article><h2>Your recent fills.</h2><div className="card activityList">{fills.length === 0 ? <p>No matched trades yet.</p> : fills.map(fill => <div key={fill.id}><span>{fill.buyOrder.userId === user.id ? "BUY" : "SELL"} • {fill.buyOrder.athlete.name}</span><strong>{Number(fill.quantity).toFixed(2)} @ {money(fill.price)}</strong><small>Value {money(fill.gross)} • Your fee {money(fill.buyOrder.userId === user.id ? fill.buyFee : fill.sellFee)}{fill.sellOrder.userId === user.id ? ` • Test realized P/L ${money(fill.sellerPnl)}` : ""}</small></div>)}</div></article><article><h2>Your cash audit.</h2><div className="card activityList">{entries.length === 0 ? <p>No test ledger activity.</p> : entries.map(entry => <div key={entry.id}><span>{entry.type.replaceAll("_", " ")}</span><strong>{money(entry.amount)} • Balance {money(entry.balance)}</strong><small>Held after event: {money(entry.reservedAfter)}</small></div>)}</div></article></section>
    <footer className="realSandboxFooter card">All cash, shares, withdrawals, and fees here are simulated. Real-money trading remains disabled. A reference valuation does not guarantee a sale or retirement payout. Test balances are separate from Free Market and older internal simulators.</footer>
  </main>;
}
