import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { isAdmin } from "@/lib/beta-controls";
import { prisma } from "@/lib/prisma";
import { realMarketSandboxPreviewEnabled } from "@/lib/real-market";

function ActionForm({ action, targetId, label }: { action: string; targetId: string; label: string }) {
  return <form className="adminAction" action="/api/admin/actions" method="post"><input type="hidden" name="action" value={action}/><input type="hidden" name="targetId" value={targetId}/><input name="reason" aria-label={`Reason to ${label.toLowerCase()}`} placeholder="Reason for action" minLength={5} maxLength={500} required/><button className="secondary">{label}</button></form>;
}

export default async function Admin({ searchParams }: { searchParams: Promise<{ q?: string; error?: string; status?: string }> }) {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  if (!isAdmin(user.id)) notFound();
  const params = await searchParams;
  const q = (params.q || "").slice(0, 100);
  const sandbox = realMarketSandboxPreviewEnabled();
  const [users, athletes, trades, audits, enrollment, providers, control, rewardCount] = await Promise.all([
    prisma.user.findMany({ where: q ? { OR: [{ username: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }] } : {}, select: { id: true, username: true, email: true, accountFrozen: true, leaderboardEligible: true, wallet: { select: { balance: true } } }, orderBy: { createdAt: "desc" }, take: 30 }),
    prisma.athlete.findMany({ where: { active: true, ...(q ? { name: { contains: q, mode: "insensitive" } } : { marketEnabled: true }) }, orderBy: { updatedAt: "desc" }, take: 30 }),
    prisma.trade.findMany({ include: { user: { select: { username: true } }, athlete: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.adminAuditEvent.findMany({ orderBy: { createdAt: "desc" }, take: 30 }),
    sandbox ? prisma.realEnrollment.findMany({ include: { user: { select: { username: true } } }, orderBy: { updatedAt: "desc" }, take: 30 }) : [],
    sandbox ? prisma.liquidityProvider.findMany({ where: { environment: "SANDBOX" }, take: 30 }) : [],
    prisma.betaControl.findUnique({ where: { id: "global" } }),
    prisma.rewardClaim.count(),
  ]);
  return <main className="shell adminPage">
    <header className="hero"><div><span className="eyebrow">OPERATIONS</span><h1>Admin console</h1><p className="muted">Account, market, and beta controls. Every change requires a reason.</p></div>{sandbox && <Link className="button secondary" href="/real-market/liquidity">Liquidity console</Link>}</header>
    {params.error && <div className="notice errorNotice" role="alert">{params.error}</div>}{params.status && <div className="notice successNotice" role="status">{params.status}</div>}
    <section className="grid stats"><article className="card"><h2>Free Market</h2><p>{control?.freeTradingPaused ? "Trading paused" : "Trading open"}</p><ActionForm action={control?.freeTradingPaused ? "RESUME_FREE" : "PAUSE_FREE"} targetId="global" label={control?.freeTradingPaused ? "Resume trading" : "Pause trading"}/></article><article className="card"><h2>Real Market sandbox</h2><p>{control?.sandboxPaused ? "Sandbox paused" : "Sandbox open"} · Live funds disabled</p><ActionForm action={control?.sandboxPaused ? "RESUME_SANDBOX" : "PAUSE_SANDBOX"} targetId="global" label={control?.sandboxPaused ? "Resume sandbox" : "Pause sandbox"}/></article><article className="card"><h2>Reward eligibility</h2><p>{rewardCount} sandbox reservation{rewardCount === 1 ? "" : "s"}</p><p className="muted">One reservation per verified identity per campaign. Reservations do not pay or credit funds.</p></article></section>
    <section className="card"><h2>Beta readiness</h2><p>Password recovery email: {process.env.AUTH_EMAIL_WEBHOOK_URL && process.env.AUTH_EMAIL_WEBHOOK_TOKEN && process.env.APP_ORIGIN ? "configured" : "configuration needed"}.</p><p>Live identity verification and live funds remain disabled. Sandbox reviews are test approvals.</p><Link href="/api/health">Check application health</Link></section>
    <form className="card adminSearch" method="get"><label htmlFor="admin-search">Find an account or athlete</label><input id="admin-search" name="q" defaultValue={q} placeholder="Username, email, or athlete name"/><button>Search</button></form>
    <section className="card"><h2>Accounts</h2><p className="muted">Showing up to 30 matching accounts. Multiple Free Market accounts are allowed.</p><div className="adminTableWrap"><table className="market"><thead><tr><th>Account</th><th>Status</th><th>Controls</th></tr></thead><tbody>{users.map((account) => <tr key={account.id}><td><strong>{account.username}</strong><p className="muted">{account.email}</p></td><td>{account.accountFrozen ? "Frozen" : "Active"}<p>{account.leaderboardEligible ? "Leaderboard eligible" : "Leaderboard excluded"}</p></td><td><ActionForm action={account.accountFrozen ? "UNFREEZE" : "FREEZE"} targetId={account.id} label={account.accountFrozen ? "Unfreeze account" : "Freeze account"}/><ActionForm action={account.leaderboardEligible ? "EXCLUDE_LEADERBOARD" : "RESTORE_LEADERBOARD"} targetId={account.id} label={account.leaderboardEligible ? "Exclude leaderboard" : "Restore leaderboard"}/></td></tr>)}</tbody></table></div>{!users.length && <p>No matching accounts.</p>}</section>
    <section className="card"><h2>Athlete controls</h2><p className="muted">Search by name to find halted athletes. These controls affect the Free Market catalog.</p><div className="adminTableWrap"><table className="market"><thead><tr><th>Athlete</th><th>Market</th><th>Control</th></tr></thead><tbody>{athletes.map((athlete) => <tr key={athlete.id}><td>{athlete.name}<p className="muted">{athlete.sport} · {athlete.team}</p></td><td>{athlete.marketEnabled ? "Enabled" : "Halted"}</td><td><ActionForm action={athlete.marketEnabled ? "HALT_ATHLETE" : "RESUME_ATHLETE"} targetId={athlete.id} label={athlete.marketEnabled ? "Halt athlete" : "Resume athlete"}/><form className="adminAction" action="/api/admin/actions" method="post"><input type="hidden" name="action" value="CORRECT_PRICE"/><input type="hidden" name="targetId" value={athlete.id}/><input type="number" name="price" min="1" max="1000000" step="0.01" defaultValue={String(athlete.currentPrice)} aria-label={`Corrected price for ${athlete.name}`} required/><input name="reason" aria-label="Price correction reason" placeholder="Correction reason" minLength={5} maxLength={500} required/><button className="secondary">Correct price</button></form></td></tr>)}</tbody></table></div></section>
    {sandbox && <section className="card"><h2>Sandbox identity reviews</h2><p className="muted">Use a consistent opaque sandbox person ID across test accounts. This simulates a provider result; it does not perform live KYC.</p><div className="adminReviewGrid">{enrollment.map((entry) => <article key={entry.id} className="adminReview"><h3>{entry.user.username}</h3><p>{entry.status}</p><form className="adminAction" action="/api/admin/actions" method="post"><input type="hidden" name="targetId" value={entry.userId}/><input name="identityToken" aria-label={`Sandbox person ID for ${entry.user.username}`} placeholder="Opaque sandbox person ID" minLength={8} maxLength={100}/><input name="reason" aria-label="Identity review reason" placeholder="Review reason" minLength={5} maxLength={500} required/><button name="action" value="VERIFY_IDENTITY">Verify sandbox identity</button><button className="secondary" name="action" value="REJECT_IDENTITY">Decline or revoke</button></form>{entry.status === "VERIFIED" && <form className="adminAction" action="/api/admin/actions" method="post"><input type="hidden" name="action" value="RESERVE_REWARD"/><input type="hidden" name="targetId" value={entry.userId}/><input name="campaign" aria-label="Reward campaign" placeholder="Campaign ID" minLength={3} maxLength={80} required/><input name="reason" aria-label="Reward reservation reason" placeholder="Reservation reason" minLength={5} maxLength={500} required/><button className="secondary">Reserve reward eligibility</button></form>}</article>)}</div>{!enrollment.length && <p>No identity reviews yet.</p>}</section>}
    {sandbox && <section className="card"><h2>Liquidity providers</h2>{providers.map((provider) => <div key={provider.id} className="adminReview"><h3>{provider.name} · {provider.status}</h3><ActionForm action="SUSPEND_LP" targetId={provider.id} label="Suspend LP and cancel quotes"/></div>)}</section>}
    <section className="card"><h2>Recent Free Market trades</h2><div className="adminTableWrap"><table className="market"><thead><tr><th>Trader</th><th>Athlete</th><th>Side</th><th>Units</th><th>Time</th></tr></thead><tbody>{trades.map((trade) => <tr key={trade.id}><td>{trade.user.username}</td><td>{trade.athlete.name}</td><td>{trade.side}</td><td>{String(trade.quantity)}</td><td>{trade.createdAt.toISOString()}</td></tr>)}</tbody></table></div></section>
    <section className="card"><h2>Audit log</h2>{audits.map((audit) => <article className="adminReview" key={audit.id}><strong>{audit.action}</strong><p>{audit.reason}</p><small>Target {audit.targetId} · Actor {audit.actorId} · {audit.createdAt.toISOString()}</small></article>)}{!audits.length && <p>No administrative actions yet.</p>}</section>
  </main>;
}
